// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwjanjishsycsmskafjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3amFuamlzaHN5Y3Ntc2thZmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4OTAwODIsImV4cCI6MjA3MzQ2NjA4Mn0.imtd5KBD9WeTdn1UeL2sd1iheZVsy2Hm40vapiU_UlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});